[package]
org = "crates"
name = "mustache"
version = "@toml.version@"
distribution = "2201.2.0"
authors = ["Mohamed Sabthar (@MohamedSabthar)"]
repository = "https://github.com/MohamedSabthar/mustache"
license = ["Apache-2.0"]

[[platform.java11.dependency]]
path = "../native/build/libs/mustache-native-@project.version@.jar"
groupId = "io.ballerina.xlibb"
artifactId = "mustache-native"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/compiler-@mustache.version@.jar"
groupId = "com.github.spullara.mustache.java"
artifactId = "compiler"
version = "@mustache.version@"
